[package]
name = "test_libc"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = "0.30.1" # Assurez-vous que cette version correspond à celle que vous utilisez
libc = "0.2"

[features]
idl-build = ["anchor-lang/idl-build"]